#!/bin/sh /etc/rc.common

START=99
STOP=01

USE_PROCD=1

start_service() {
    echo "Starting fan monitor instance..."
    procd_open_instance
    procd_set_param command /usr/sbin/fan_monitor
    procd_set_param respawn
    procd_set_param respawn_delay 5
    procd_close_instance
}

start() {
    board_id=$(cat /tmp/sysinfo/board_name)

    case "$board_id" in
        "glient,gl-axt1800")
            start_service
            ;;
        *)
            echo "Unsupported board. Fan control not available."
            ;;
    esac
}

stop() {
    board_id=$(cat /tmp/sysinfo/board_name)

    case "$board_id" in
        "glient,gl-axt1800")
            echo "Stopping fan monitor instance..."
            procd_kill_instance
            ;;
        *)
            echo "Unsupported board. Fan control not available."
            ;;
    esac
}

reload() {
    board_id=$(cat /tmp/sysinfo/board_name)

    case "$board_id" in
        "glient,gl-axt1800")
            echo "Reloading fan monitor instance..."
            procd_reload_instance
            ;;
        *)
            echo "Unsupported board. Fan control not available."
            ;;
    esac
}
